[[redirects]]
from = "https://nickyt.live/talks"
to = "https://www.nickyt.co/talks"
status = 302
force = true

[[redirects]]
from = "https://nickyt.live/talks/"
to = "https://www.nickyt.co/talks/"
status = 302
force = true

[[redirects]]
from = "https://nickyt.live/talks/*"
to = "https://www.nickyt.co/talks/:splat"
status = 302
force = true

[[redirects]]
from = "https://nickyt.live/about"
to = "https://www.nickyt.co/about"
status = 302
force = true

[[redirects]]
from = "https://nickyt.live/about/"
to = "https://www.nickyt.co/about/"
status = 302
force = true

[[redirects]]
from = "https://nickyt.live/*"
to = "https://www.nickyt.co/:splat"
status = 302
force = true
